let arr = [];
arr.push(10);
arr.push(20);
arr.push(30);
arr.push(40);
arr.push(50);
arr.push(60);
console.log(arr);
arr.pop();
console.log(arr);
arr[2] = 60;
console.log(arr);
arr.splice(1, 1);
console.log(arr);
arr.sort((a, b) => b - a);
console.log(arr);
let maxVal = Math.max(...arr);
console.log("ค่ามากที่สุด: " + maxVal);
let minVal = Math.min(...arr);
console.log("ค่าน้อยที่สุด: " + minVal);